apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: "master-datavol"
spec:
  source:
      http:
         url: "http://10.193.138.160:8080/stretch-kubeadm-kvm.qcow2"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "50Gi"
